
export const API_BASE =
  process.env.REACT_APP_API_URL || "http://localhost:8000";

export const TASKS = {
  lpr: {
    id: "lpr",
    label: "License Plate Recognition",
    short: "LPR",
    description: "Read and log plates",
    color: "#22d3ee",
    glow: "rgba(34,211,238,0.25)",
    endpoints: {
      image: `${API_BASE}/api/lpr/image`,
      imageAnnotated: `${API_BASE}/api/lpr/image/annotated`,
      video: `${API_BASE}/api/lpr/video`,
      videoAnalyze: `${API_BASE}/api/lpr/video/analyze`,
      demoImage: `${API_BASE}/api/lpr/demo/image`,
      demoImageAnn: `${API_BASE}/api/lpr/demo/image/annotated`,
      demoVideo: `${API_BASE}/api/lpr/demo/video`,
      cameraLive: `${API_BASE}/api/stream/lpr`,
      sessions: `${API_BASE}/api/lpr/sessions`,
      metrics: `${API_BASE}/api/lpr/metrics`,
    },
    available: true,
  },
  vpd: {
    id: "vpd",
    label: "Vehicle & Person Detection",
    short: "VPD",
    description: "Identify vehicle and users",
    color: "#4ade80",
    glow: "rgba(74,222,128,0.25)",
    endpoints: {
      image: `${API_BASE}/api/vpd/image`,
      imageAnnotated: `${API_BASE}/api/vpd/image/annotated`,
      video: `${API_BASE}/api/vpd/video`,
      videoAnalyze: `${API_BASE}/api/vpd/video/analyze`,
      demoImage: `${API_BASE}/api/vpd/demo/image`,
      demoImageAnn: `${API_BASE}/api/vpd/demo/image/annotated`,
      demoVideo: `${API_BASE}/api/vpd/demo/video`,
      cameraLive: `${API_BASE}/api/stream/vpd`,
      sessions: `${API_BASE}/api/vpd/sessions`,
      metrics: `${API_BASE}/api/vpd/metrics`,
    },
    available: true,
  },
  vid: {
    id: "vid",
    label: "Violation Detection",
    short: "VID",
    description: "Detect traffic rule violations",
    color: "#fb923c",
    glow: "rgba(251,146,60,0.25)",
    endpoints: {
      image: `${API_BASE}/api/vid/image`,
      imageAnnotated: `${API_BASE}/api/vid/image/annotated`,
      video: `${API_BASE}/api/vid/video`,
      videoAnalyze: `${API_BASE}/api/vid/video/analyze`,
      demoImage: `${API_BASE}/api/vid/demo/image`,
      demoImageAnn: `${API_BASE}/api/vid/demo/image/annotated`,
      demoVideo: `${API_BASE}/api/vid/demo/video`,
      cameraLive: `${API_BASE}/api/stream/vid`,
      sessions: `${API_BASE}/api/vid/sessions`,
      metrics: `${API_BASE}/api/vid/metrics`,
    },
    available: true,
  },
};

export const INPUT_MODES = [
  {
    id: "upload_image",
    label: "Upload Image",
    icon: "ImagePlus",
    desc: "JPG · PNG · WebP",
    group: "static",
  },
  {
    id: "upload_video",
    label: "Upload Video",
    icon: "FileVideo",
    desc: "MP4 · AVI · MOV",
    group: "static",
  },
  {
    id: "demo_image",
    label: "Demo Image",
    icon: "Sparkles",
    desc: "Preloaded sample",
    group: "demo",
  },
  {
    id: "demo_video",
    label: "Demo Video",
    icon: "PlayCircle",
    desc: "Preloaded sample",
    group: "demo",
  },
  {
    id: "camera_image",
    label: "Capture Photo",
    icon: "Camera",
    desc: "Single webcam frame",
    group: "live",
  },
  {
    id: "camera_video",
    label: "Live Stream",
    icon: "Radio",
    desc: "Instant analysis",
    group: "live",
  },
];
